apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels:
        app: myapp
        type: front-end

spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: front-end
        spec:
                containers:
                 - name: gauravaord
                   image: gaurav1983/gaurav:1.1.5
                 
    replicas: 3
    selector:
        matchLabels:
            type: front-end         
    

