apiVersion: v1
kind: Namespace
metadata:
  name: aordprod
---
apiVersion: v1
kind: ResourceQuota
metadata:
    name: compute-quota
    namespace: aordprod
spec:
    hard:
        pods: "4"
        requests.cpu: "2"
        requests.memory: 2Gi
        limits.cpu: "10"
        limits.memory: 3Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: prod-vol1
    namespace: aordprod
spec:
    accessModes:
        - ReadWriteMany
    capacity:
        storage: 50Gi
    gcePersistentDisk:
        pdName: prod-vol
        fsType: ext4        
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: myclaim
    namespace: aordprod
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 50Gi                
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    namespace: aordprod
    labels:
        app: myapp
        type: front-end

spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: front-end
        spec:
                containers:
                 - name: httpd-php-container
                   image: wlniao/php
                   resources:
                      limits:
                        memory: "800Mi"
                        cpu: "800m" 
                      requests:
                        memory: "600Mi"
                        cpu: "400m"
                   ports:
                    - containerPort: 80
                   volumeMounts:
                    - name: prod-persistent-storage
                      mountPath: "/var/www/html"
                volumes:
                   - name: prod-persistent-storage
                     persistentVolumeClaim:
                        claimName: myclaim          
    replicas: 2
    selector:
        matchLabels:
            type: front-end    
---
apiVersion: v1
kind: Service
metadata:
  name: aordprodloadbalancer
  namespace: aordprod
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http    
  selector:
            app: myapp
            type: front-end      


            
    
