apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp-deployment
    labels:
        app: myapp
        type: front-end

spec:
    template:
        metadata:
            name: myapp-pod
            labels:
                app: myapp
                type: front-end
        spec:
                containers:
                 - name: myappjenkins
                   image: nginx:1.17.8
                   type: LoadBalancer

                 
    replicas: 3
    selector:
        matchLabels:
            type: front-end         
    

